apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-yangju
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/splex7/argocd-example-apps.git
    targetRevision: HEAD
    path: helloworld-yangju
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
