apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
spec:	
  type: Nodeport
  ports:	
  - port: 80	
    targetPort: 80
    protocol: TCP
    nodePort: 31001
  selector:	
    app: guestbook-ui
